### Register Admin
POST http://localhost:8080/api/users/admin
Accept: application/json
Content-Type: application/json

{
  "name": "GALEH",
  "email": "3130021003@student.unusa.ac.id",
  "password": "rahasia"
}

### Register User
POST http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "name": "Amelia Wardana",
  "email": "kigaleh321@gmail.com",
  "gender": "perempuan",
  "tempat_lahir": "Labuan Bajo",
  "birthDate": "2002-10-10",
  "category": "M",
  "instansi": "Kedokteran",
  "anamnesa": "Nyeri Otot",
  "pemeriksaan": "Kesleo Otot",
  "diagnosis": "Gangguan Jiwa",
  "therapy": "Lurusin Otot",
  "therapy2": "P",
  "totalObat": 10,
  "totalObat": 20
}

### Login
POST http://localhost:8080/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "3130021004@student.unusa.ac.id",
  "password": "YFEQDEZD"
}

### Get User Current
GET http://localhost:8080/api/users/current
Accept: application/json
X-API-TOKEN: 66d5af46-0d0a-4409-b5a3-aa86d7106190

### Get List User
GET http://localhost:8080/api/users
Accept: application/json


### Search User (bermasalah data muncul semua)
GET http://localhost:8080/api/users/search?instansi=Sistem Informasi
Accept: application/json

### Get total pengunjung
GET http://localhost:8080/api/users/total
Accept: application/json

### Logout
DELETE http://localhost:8080/api/auth/logout
Accept: application/json
x-API-TOKEN: 6b8a4b91-875e-4726-bcab-868e44bb4b8a

### Add rekam medis
POST http://localhost:8080/api/rm/K8
Accept: application/json
Content-Type: application/json

{
  "anamnesa": "Pusing",
  "pemeriksaan": "",
  "diagnosis": "Migrain",
  "therapy": "Tidur aja",
  "therapy2": "Tidur lagi",
  "therapy3": "eh Tidur",
  "jumlahObat": 8,
  "jumlahObat2": 8,
  "jumlahObat3": 8
}

### Get Rekam Medis
GET http://localhost:8080/api/rm/M3

### Add Obat
POST http://localhost:8080/api/obat
Accept: application/json
Content-Type: application/json

{
  "nameObat": "Bapak Phropent 2",
  "expired": "10-10-2029",
  "minStock": 20,
  "stock": 100
}

### Get List Obat
GET http://localhost:8080/api/obat
Accept: application/json
Content-Type: application/json

### Get List Obat
GET http://localhost:8080/api/nameObat
Accept: application/json
Content-Type: application/json



